language: generic
sudo: required
services:
  - docker

before_install:
  - docker pull fedora
  - docker run --name fedora -it -d fedora /bin/bash
env:
  - PLATFORM=linux
  - PLATFORM=win64
  - PLATFORM=win32
  - PLATFORM=android
  - PLATFORM=android-gles3

script:
  - docker exec fedora dnf -q -y update
  - docker exec fedora dnf -q -y install make git gcc-c++ mesa-libGL-devel mingw64-gcc-c++ mingw64-zlib mingw32-gcc-c++ mingw32-zlib mingw64-libpng mingw32-libpng zlib-devel flex bison wget unzip zip python awscli nasm libpng-devel
  - docker exec fedora /bin/bash -c "if [[ $PLATFORM == "android*" ]]; then wget -q https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip; unzip -qq android-ndk-r13b-linux-x86_64.zip; ./android-ndk-r13b/build/tools/make_standalone_toolchain.py --arch arm --api 18 --install-dir /mychain; fi"
  - docker exec fedora git clone --depth 25 -b $TRAVIS_BRANCH https://github.com/GLupeN64/GLupeN64.git
  - docker exec fedora /bin/bash -c "export PATH=$PATH:/mychain/bin; cd GLupeN64; if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then git checkout $TRAVIS_COMMIT; else git fetch origin pull/$TRAVIS_PULL_REQUEST/head:temp; git checkout temp; fi; platform=$PLATFORM make"
  - docker exec fedora /bin/bash -c "cd GLupeN64; zip glupen64_$PLATFORM.zip glupen64_*"
  - docker exec fedora /bin/bash -c "export AWS_ACCESS_KEY_ID=$ACCESS_KEY; export AWS_SECRET_ACCESS_KEY=$SECRET_KEY; cd GLupeN64; if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then aws s3 cp glupen64_$PLATFORM.zip s3://loganbuildbot/cores/ --acl public-read; fi"
